# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_acts_as}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["phinze"]
  s.date = %q{2010-01-11}
  s.description = %q{Generate temporary tables and models, specify defined
      and required methods, all sorts of fun stuff!}
  s.email = %q{paul.t.hinze@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/acts_as_acts_as.rb",
     "lib/acts_as_acts_as/group_macros.rb",
     "lib/acts_as_acts_as/macros.rb",
     "lib/acts_as_acts_as/requirements.rb",
     "lib/acts_as_acts_as/requirements/collector.rb",
     "lib/acts_as_acts_as/requirements/verifier.rb",
     "spec/acts_as_acts_as_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/phinze/acts_as_acts_as}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Testing harness for acts_as plugins}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/acts_as_acts_as_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

